# Generated by Django 5.1.7 on 2025-04-05 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('main_weather', models.CharField(max_length=50)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('timezone_offset', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('city', 'country_code')},
            },
        ),
    ]
